apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-svc
  labels:
    apps.kubernetes.io/name: rethinkdb-svc
spec:
  selector:
    app.kubernetes.io/name: rethinkdb
  ports:
  - name: admin
    protocol: TCP
    targetPort: 8080
    port: 8080
  - name: driver
    protocol: TCP
    targetPort: 28015
    port: 28015
  - name: cluster
    protocol: TCP
    targetPort: 29015
    port: 29015
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rethinkdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rethinkdb
    spec:
      hostname: rethinkdb-openstf
      containers: 
      - name: rethinkdb
        image: registry.hub.docker.com/library/rethinkdb:centos
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: admin
        - containerPort: 28015
          name: driver
        - containerPort: 29015
          name: cluster
---
