{{- $root := . -}}
{{- range $type := .Values.emulators.types }}
{{- range $emu := .instances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" $root }}-provider-{{ $type.name }}-{{ $emu.version }}
spec:
  selector:
    matchLabels:
        app: {{ template "fullname" $root }}-provider-{{ $type.name }}-{{ $emu.version }}
  replicas: {{ $emu.count }}
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: {{ template "fullname" $root }}-provider-{{ $type.name }}-{{ $emu.version }}
    spec:
      shareProcessNamespace: true
      containers:
        - name: adb-butler
          image: {{ $root.Values.adb.image.repository }}:{{ $root.Values.adb.image.tag }}
          imagePullPolicy: {{ $root.Values.adb.image.pullPolicy }}
          resources:
{{ toYaml $root.Values.adb.resources | indent 12 }}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/node", "clean.js" ]
          securityContext:
              privileged: true
          env:
          - name: RETHINKDB_URL
            value: "{{ $root.Values.db.url }}"
          - name: RETHINKDB_PORT
            value: "{{ $root.Values.db.port }}"
          - name: RETHINKDB_ENV_AUTHKEY
            value: "{{ $root.Values.db.password }}"
          {{ if $type.timezone }}
          - name: EMULATOR_TIMEZONE
            value: "{{ $type.timezone }}"
          {{ end }}
          - name: STF_PROVIDER_PUBLIC_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: STF_PROVIDER_NOTE
            value: "{{ $type.note }}"
          envFrom:
          - configMapRef:
              name: "{{ template "fullname" $root }}-common-environment-variables"
        - name: stf-provider
          image: {{ $root.Values.stf.image.repository }}:{{ $root.Values.stf.image.tag }}
          imagePullPolicy: {{ $root.Values.stf.image.pullPolicy }}
          args:
          - /bin/sh
          - -c
          - sleep 10 && stf provider "$(STF_PROVIDER_PUBLIC_IP):10001" --connect-sub "tcp://{{ template "fullname" $root }}-triproxy-dev:7250" --connect-push "tcp://{{ template "fullname" $root }}-triproxy-dev:7270" --min-port "15000" --max-port "25000" --heartbeat-interval "10000" --storage-url "http://{{ $root.Values.ingress.hostname }}/" --screen-ws-url-pattern "wss://{{ $root.Values.ingress.hostname }}/<%= serial %>/<%= publicPort %>/" --allow-remote --cleanup "false" 2>&1 | tee /var/log/stf/messages
          env:
          - name: RETHINKDB_PORT_28015_TCP
            value: "tcp://{{ $root.Values.db.url }}:{{ $root.Values.db.port }}"
          - name: RETHINKDB_ENV_AUTHKEY
            value: "{{ $root.Values.db.password }}"
          - name: STF_PROVIDER_PUBLIC_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          envFrom:
          - configMapRef:
              name: "{{ template "fullname" $root }}-common-environment-variables"
          resources:
{{ toYaml $root.Values.provider.emulator.resources | indent 12 }}
          volumeMounts:
          - mountPath: /var/log/stf
            name: logs
      volumes:
      - name: stf-adb
        hostPath:
          path: /dev/bus/usb
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: {{ $root.Values.pullSecret }}
---
{{- end }}
{{- end }}
