apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-nginx
  name: {{ template "fullname" . }}-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ template "fullname" . }}-nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-api
  name: {{ template "fullname" . }}-api
spec:
  ports:
   - port: 3700
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-app
  name: {{ template "fullname" . }}-app
spec:
  ports:
   - port: 3100
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-auth
  name: {{ template "fullname" . }}-auth
spec:
  ports:
   - port: 3200
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-apk-storage
  name: {{ template "fullname" . }}-apk-storage
spec:
  ports:
   - port: 3300
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-apk-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-img-storage
  name: {{ template "fullname" . }}-img-storage
spec:
  ports:
   - port: 3400
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-img-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-storage
  name: {{ template "fullname" . }}-storage
spec:
  ports:
   - port: 3500
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-triproxy-app
  name: {{ template "fullname" . }}-triproxy-app
spec:
  ports:
   - port: 7150
     targetPort: 7150
     name: bind-pub
   - port: 7160
     targetPort: 7160
     name: bind-dealer
   - port: 7170
     targetPort: 7170
     name: bind-pull
  selector:
    app: {{ template "fullname" . }}-triproxy-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-triproxy-dev
  name: {{ template "fullname" . }}-triproxy-dev
spec:
  ports:
   - port: 7250
     targetPort: 7250
     name: bind-pub
   - port: 7260
     targetPort: 7260
     name: bind-dealer
   - port: 7270
     targetPort: 7270
     name: bind-pull
  selector:
    app: {{ template "fullname" . }}-triproxy-dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-websocket
  name: {{ template "fullname" . }}-websocket
spec:
  ports:
   - port: 3600
     targetPort: 3000
  selector:
    app: {{ template "fullname" . }}-websocket
